include: package:lints/recommended.yaml


linter:
  rules:
    - package_api_docs

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/src/**.g.dart
    - lib/src/**.freezed.dart