name: dero_rpc_api
description: Dero RPC API (derod and wallet) to interact with Dero network.
version: 0.12.3

repository: https://github.com/Ez3kiel-dev/dero_rpc_api

environment:
  sdk: '>=3.4.0'

dependencies:
  convert: ^3.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_rpc_2: ^3.0.2
  very_good_analysis: ^5.1.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.5
