name: dero_rpc_api
description: Dero RPC API (derod and wallet) to interact with Dero network.
version: 0.1.4

repository: https://github.com/Ez3kiel-dev/dero_rpc_api

funding:
  - https://www.buymeacoffee.com/ez3kiel

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  convert: ^3.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  json_rpc_2: ^3.0.2
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.0