name: dero_rpc_api
description: Dero RPC API (derod and wallet) to interact with Dero network.
version: 0.12.2

repository: https://github.com/Ez3kiel-dev/dero_rpc_api

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_rpc_2: ^3.0.2
  very_good_analysis: ^5.1.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.1
